pipeline {
    agent any

    environment {
        VENV = 'venv'
        OUTPUT_FILE = 'output.txt'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set Up Python') {
            steps {
                script {
                    sh 'sudo apt-get update'
                    sh 'sudo apt-get install -y python3 python3-venv'
                    sh "python3 -m venv ${VENV}"
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir('my_ml_project') {
                        sh """
                            source ${VENV}/bin/activate
                            pip install -r requirements.txt
                            python3 -m pytest tests
                        """
                    }
                }
            }
        }
        stage('Run ML Script') {
            steps {
                script {
                    dir('my_ml_project') {
                        sh """
                        . ${VENV}/bin/activate
                        python3 src/my_ml_script.py > ${OUTPUT_FILE} || (echo 'Error running ML script: \$?'; exit 1)
                        """
                    }
                }
            }
        }

        stage('Deployment') {
            steps {
                script {
                    sh "cp ${OUTPUT_FILE} D:/LAB7/my_ml_project/${OUTPUT_FILE}"
                }
            }
        }

        stage('Deactivate Virtual Environment') {
            steps {
                script {
                    sh "deactivate || true"
                }
            }
        }
    }
}






















