pipeline {
    agent any

    environment {
        VENV = 'venv'
        OUTPUT_FILE = 'output.txt'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set Up Python') {
            steps {
                script {
                    sh 'sudo apt-get update'
                    sh 'sudo apt-get install -y python3 python3-venv'
                    sh 'python3 -m venv venv'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    // Set the working directory to the project root
                    dir('my_ml_project') {
                        // Activate the virtual environment and run your tests using pytest
                        sh 'source ../venv/bin/activate && python -m pytest tests'
                    }
                }
            }
        }

        stage('Run ML Script') {
            steps {
                script {
                    // Run your ML script within the virtual environment
                    sh "bash -c '. venv/bin/activate && python my_ml_project/src/my_ml_script.py > ${OUTPUT_FILE}'"
                }
            }
        }

        stage('Deployment') {
            steps {
                script {
                    // Upload the output file to a desired location
                    sh "cp ${OUTPUT_FILE} D:/LAB7/my_ml_project/${OUTPUT_FILE}"
                }
            }
        }

        stage('Deactivate Virtual Environment') {
            steps {
                script {
                    // Deactivate virtual environment after execution
                    sh "deactivate || true"
                }
            }
        }
    }
}
















